export const Header: string;
export const header: string;
export const Heading: string;
export const heading: string;
export const NavMenu: string;
export const navMenu: string;
export const Link: string;
export const link: string;
export const activeItem: string;
